### ISSUE TITLE
Add View.each() false return usage notes to tutorial and docs

### ISSUE THREAD

**Issue by vegeta897** [jprochazk/uecs#3]
I noticed that the View.each() method accepts `false` as a return value, in addition to `void`. I was pleased to discover that returning `false` causes iteration to stop. This is very handy! But I don't see mention of it anywhere in the tutorial or docs (the `each()` method itself is not even in the docs).

**Comment by jprochazk** [comment]
I'll export the `View` interface and add a mention of it in the tutorial.

**Comment by jprochazk** [comment]
Fixed in 77233a7.

**Comment by jprochazk** [comment]
Included this in release v0.3.0.
