### ISSUE TITLE
Recommended pooling library? Example implementation?

### ISSUE THREAD

**Issue by vegeta897** [jprochazk/uecs#5]
In the [tutorial](https://jan-prochazka.eu/uecs/tutorial#working-with-components), it is mentioned that object pooling can be handled by the user, and that there are plenty of existing libraries for this.

I for one would be very grateful to see a specific library recommended, and perhaps even a barebones example of how it would be implemented alongside uecs. 🙏

**Comment by jprochazk** [comment]
Hi, looking up [`object pool` on npm](https://www.npmjs.com/search?q=object+pool) yields quite a few results, I'm sure you can find one to your liking. I don't have any specific recommendation.

From the point of view of this library, all you need to be able to do is instantiate the components, and give them to the `World` when emplacing components. If the library supports the `.free()` method for re-using components, then it will work out of the box. If not, then you need the component to hold a reference to the pool, and make `.free()` return `this` to the pool.

An example using the [first result](https://www.npmjs.com/package/@jacekpietal/object-pool) from the above npm search (disclaimer: I've never used this library)

```ts
class Component {
  private initialized = false;
  constructor(
    // ideally, this would be a weak reference
    private pool: ObjectPool,
    // you would replace this with whatever arguments your component has
    ...args: any[]
  ) {
    // initialization is deferred to the .init method
    this.init(...args);
  }
  init(...args: any[]) {
    if (this.inititalized) return;
    console.log("initialized with", args);
    this.initialized = true;
    return this;
  }
  free() {
    this.initialized = false;
    this.pool.put(this);
  }
}

const pool = new ObjectPool(() => new Component(pool));
const world = new World;
for (let i = 0; i < 100; ++i) {
  world.create(pool.get().init(i));
}
world.view(Component).each((_, c) => { /* use c */ });
for (const entity of world.all()) {
  world.destroy(entity);
}
```

**Comment by vegeta897** [comment]
Much appreciated, I guess I gave up too early being intimidated by all the library options in an area I was unfamiliar with. I will give it a better attempt. Thank you!
