### ISSUE TITLE
Issue with insert

### ISSUE THREAD

**Issue by K4ST0R** [jprochazk/uecs#7]
I think there is an issue with insert.

https://github.com/jprochazk/uecs/blob/5d56d2a1fb1cc9e6178a4800d8097b55adf11064/src/world.ts#L85

`if (entity > this.entitySequence) this.entitySequence = entity + 1;` should be `if (entity >= this.entitySequence) this.entitySequence = entity + 1;`

Currently if we call a create after an insert, the create will have the same id than the last insert.

**Comment by jprochazk** [comment]
Thank you for reporting this. I published [`0.4.2`](https://github.com/jprochazk/uecs/releases/tag/v0.4.2) with the fix.
